### ISSUE TITLE
Make it work under Windows

### ISSUE THREAD

**Issue by kovalp** [kovalp/sisl_approach_f2py#3]

**Comment by kovalp** [comment]
@zerothi In this example, cython is not used. I suspect the approach of sisl is even more sophisticated than in this module.

When compiling under Windows, gcc is used this time. It is still failing, but the error message is understandable.
[pip.out.txt](https://github.com/kovalp/sisl_approach_f2py/files/5000580/pip.out.txt)

**Comment by kovalp** [comment]
Good news!

I upgraded pip, numpy (scipy and matplotlib as well) and then I has been able to compile a working package1.

[pip.out.txt](https://github.com/kovalp/sisl_approach_f2py/files/5000636/pip.out.txt)

**Comment by zerothi** [comment]
Could you also import it? That is where it may go wrong ;)

**Comment by kovalp** [comment]
Of course, I checked

python -c "import package1; package1.hello_world()"

is printing the aliens hello.

**Comment by kovalp** [comment]
```
koval@DESKTOP-B5CLTB9 MINGW64 ~
$ python -c "import package1; package1.hello_world()"
 tshetsh

```

**Comment by zerothi** [comment]
Ah! Great! :+1: 
Ok, did you then try sisl with the updated numpy etc? Possibly the changes could be because you have now installed the C compiler and thus the libraries have changed in the latest numpy installation?

I.e. try everything from scratch with `sisl` seems like a good idea. If this does not work, I can add Cython to this branch?

**Comment by kovalp** [comment]
However, when installing sisl, the module sisl is not importable, with the same error. I also saw that the visual studio's C compiler has been used.

[pip.out.txt](https://github.com/kovalp/sisl_approach_f2py/files/5000685/pip.out.txt)

**Comment by zerothi** [comment]
Yeah, try everything from a clean slate. I remember you installed numpy before the C compiler? No?

**Comment by kovalp** [comment]
I was using this command to install sisl

`pip install -vvv --no-cache-dir --no-deps --no-index --no-build-isolation --compile --global-option build --global-option --compiler=mingw32 --global-option --fcompiler=gnu95 . &>pip.out.txt
`

Is this clean? How to start from a clean state, please?

**Comment by zerothi** [comment]
What `pip` command did you use for this package?

**Comment by kovalp** [comment]
```
$ pip --version
pip 20.2 from c:\users\koval\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)

```

**Comment by zerothi** [comment]
No, what exact command line did you use `pip install ...`?

**Comment by kovalp** [comment]
I used this command https://github.com/kovalp/sisl_approach_f2py/issues/3#issuecomment-666289973

for both sisl and sisl_approach_f2py

**Comment by kovalp** [comment]
The setup of sisl_approach_f2py obeyed the --compiler=mingw32 option and used gcc compiler (provided by mingw64). On the contrary, sisl did not obey the option --compiler=mingw32 and used the Visual Studio's C/C++ compiler instead.

**Comment by kovalp** [comment]
Adding to setup.cfg a [build] section with compiler=mingw32 and fcompiler=gfortran improves the consistency among build and install steps.
